# Generated by Django 3.2.11 on 2022-11-25 19:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='prediction_photo/profile', verbose_name='Фото')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Запрос с фото',
                'verbose_name_plural': 'Запросы с фото',
            },
        ),
        migrations.CreateModel(
            name='RequestPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='prediction_photo/profile', verbose_name='Фото')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Запрос с опросом',
                'verbose_name_plural': 'Запросы с опросом',
            },
        ),
        migrations.RemoveField(
            model_name='predictionpoll',
            name='diseases',
        ),
        migrations.RemoveField(
            model_name='predictionpoll',
            name='pet',
        ),
        migrations.AlterModelOptions(
            name='diseases',
            options={'verbose_name': 'Болезнь', 'verbose_name_plural': 'Болезни'},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name': 'Питомец', 'verbose_name_plural': 'Питомцы'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль владельца', 'verbose_name_plural': 'Профили владельца'},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='second_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='third_name',
        ),
        migrations.AlterField(
            model_name='diseases',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='diseases',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Вес'),
        ),
        migrations.DeleteModel(
            name='PredictionPhoto',
        ),
        migrations.DeleteModel(
            name='PredictionPoll',
        ),
        migrations.AddField(
            model_name='requestpoll',
            name='diseases',
            field=models.ManyToManyField(to='pet.Diseases', verbose_name='Болезни'),
        ),
        migrations.AddField(
            model_name='requestpoll',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_poll_pet', to='pet.pet', verbose_name='Питомец'),
        ),
        migrations.AddField(
            model_name='requestphoto',
            name='diseases',
            field=models.ManyToManyField(to='pet.Diseases', verbose_name='Болезни'),
        ),
        migrations.AddField(
            model_name='requestphoto',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_photo_pet', to='pet.pet', verbose_name='Питомец'),
        ),
    ]
