# Generated by Django 3.2.11 on 2022-11-25 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_alter_pet_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='owner',
            new_name='user',
        ),
    ]
