# Generated by Django 3.2.11 on 2022-11-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_rename_owner_pet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestphoto',
            name='status',
            field=models.CharField(blank=True, choices=[('filter', 'Фильтр пройден'), ('received', 'Фото получено'), ('end', 'Ответ получен'), ('init', 'Форма создана')], default='init', max_length=32, verbose_name='Статус запроса'),
        ),
    ]
