# Generated by Django 3.2.11 on 2022-11-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_requestphoto_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestphoto',
            name='status',
            field=models.CharField(blank=True, choices=[('received', 'Фото получено'), ('filter', 'Фильтр пройден'), ('end', 'Ответ получен'), ('init', 'Форма создана')], default='init', max_length=32, verbose_name='Статус запроса'),
        ),
    ]
