# Generated by Django 3.2.11 on 2022-11-26 20:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0007_alter_requestphoto_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestphoto',
            name='status',
            field=models.CharField(blank=True, choices=[('filter', 'Фильтр пройден'), ('init', 'Форма создана'), ('received', 'Фото получено'), ('predictor', 'Ответ получен')], default='init', max_length=32, verbose_name='Статус запроса'),
        ),
        migrations.CreateModel(
            name='QuickRequestPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='prediction_photo/profile', verbose_name='Фото')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания')),
                ('status', models.CharField(blank=True, choices=[('filter', 'Фильтр пройден'), ('init', 'Форма создана'), ('received', 'Фото получено'), ('predictor', 'Ответ получен')], default='init', max_length=32, verbose_name='Статус запроса')),
                ('diseases', models.ManyToManyField(to='pet.Diseases', verbose_name='Болезни')),
            ],
        ),
    ]
