# Generated by Django 3.2.11 on 2022-11-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0008_auto_20221126_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseases',
            name='label',
            field=models.CharField(default=1, max_length=100, verbose_name='Короткое название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quickrequestphoto',
            name='status',
            field=models.CharField(blank=True, choices=[('predictor', 'Ответ получен'), ('init', 'Форма создана'), ('received', 'Фото получено'), ('filter', 'Фильтр пройден')], default='init', max_length=32, verbose_name='Статус запроса'),
        ),
        migrations.AlterField(
            model_name='requestphoto',
            name='status',
            field=models.CharField(blank=True, choices=[('predictor', 'Ответ получен'), ('init', 'Форма создана'), ('received', 'Фото получено'), ('filter', 'Фильтр пройден')], default='init', max_length=32, verbose_name='Статус запроса'),
        ),
    ]
