# Generated by Django 3.2.11 on 2022-12-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0009_auto_20221128_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseases',
            name='more_information',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='quickrequestphoto',
            name='status',
            field=models.CharField(blank=True, choices=[('predictor', 'Ответ получен'), ('init', 'Форма создана'), ('filter', 'Фильтр пройден'), ('received', 'Фото получено')], default='init', max_length=32, verbose_name='Статус запроса'),
        ),
        migrations.AlterField(
            model_name='requestphoto',
            name='status',
            field=models.CharField(blank=True, choices=[('predictor', 'Ответ получен'), ('init', 'Форма создана'), ('filter', 'Фильтр пройден'), ('received', 'Фото получено')], default='init', max_length=32, verbose_name='Статус запроса'),
        ),
    ]
